CREATE DATABASE ARP_Scan;

USE ARP_Scan;

CREATE TABLE PC
(
    /*PC_Id INT NOT NULL AUTO_INCREMENT,*/
    IP_Address VARCHAR(15) NOT NULL,
    MAC_Address VARCHAR(17) NOT NULL
    /*PRIMARY KEY (PC_Id)*/
);